## Broadcasting 
pattern used when dealing with operations between elements with different shapes <br>
ex 2x2 + 1x1 --> [[2,3],[4,3]] + [1] -> [[2,3],[4,3]] + [[1,1],[1,1]] <br>
ex 2x2 + 1x2 --> [[2,3],[4,3]] + [1,2] -> [[2,3],[4,3]] + [[1,2],[1,2]] repeats to match the shape <br>
ex 2x2 + 1x2 --> [[2,3],[4,3]] + [[1],[2]] -> [[2,3],[4,3]] + [[1,1],[2,2]] repeats to match the shape

<br><br>
There are two rules of broadcasting:
<ul>
<li>Look at the shape -> if different -> take the array with the least dimension and append at the end of the dimension, until they have the same number of dimension</li>
<li>Now check if all the dimension match to each other -> dim1A = dim1B, dim2A = dim2B -> if a number of element along a dimension doesn't match, then we repeat the array with the one dimension as may time as we need to match the other arrays' dimension, if it is not one is tricky since the may not match ex dim2A = 2 and dim2B=3 so better to avoid -> <b>Cannot broadcast the shaper together </b> </li>
</ul>



In [43]:
import numpy as np

A = np.array([1, 2, 3])
B = np.array([[11], [22], [33]])
print(A+B)
print(A.shape, B.shape)
#print([A].shape)
print(np.array([A]).shape)
A = np.array([A, A, A])
print(A+B)

x = np.random.random((3,2))
y = np.random.random((2,3))
# print(x+y)

[[12 13 14]
 [23 24 25]
 [34 35 36]]
(3,) (3, 1)
(1, 3)
[[12 13 14]
 [23 24 25]
 [34 35 36]]


## Arrays indexing

how to index arrays in numpy, can be accessed in many ways 
<ol>
<li>Simple indexing: reads/write access to an array v[i], A[i, j], A[i, j, k], assignment of values works as expected, negative indexes are welcome</li>
<li>Slicing: slicing as done in python, you can omit start, stop and/or step</li>
<li>Masking: doing the mask as said below, it creates a copy</li>
<li>Fancy indexing: we specify the index we want to select along each dimension so [x_index = [], y_index = []]
which is usually combined with other type of indexing</li>
<li>Combined indexing: a mix and match of all the previous indexing</li>
</ol>

In [54]:
v = np.random.random((10))
A = np.random.random((5,4))
print(v[1])
# rows, columns
print(A[1:3, :])
print(v[3:7])
print(A)
print(A[[0,3],[0,2]])


0.23640598245839772
[[0.31384738 0.69380416 0.92768064 0.74817894]
 [0.95591939 0.29804458 0.50129692 0.70071374]]
[0.76959281 0.74577434 0.70743251 0.06694212]
[[0.4016083  0.08829462 0.13963481 0.4340723 ]
 [0.31384738 0.69380416 0.92768064 0.74817894]
 [0.95591939 0.29804458 0.50129692 0.70071374]
 [0.70560447 0.80568832 0.56353839 0.9617476 ]
 [0.20443947 0.94426865 0.21279991 0.19377001]]
[0.4016083  0.56353839]


## Masking
use boolean mask with the same size as the array i want to index that is used to understand if a certain element meets the condition, we then apply the mask to the original matrix to then discard false elements, a 1D is always returned as a row vector

In [52]:
x = np.random.random((3,2))
mask = [[True, False], [True, False], [False, True]]
# NOT TO USE MASK 2, ITs FANCY INDEXING NOT A MASK !!!
mask2 = [[1, 0], [1, 0], [0, 1]]
print(x, x[mask], sep="\n")
print(x[mask2])

# ex every value grater than 0.5 is mapped as 10
# we can directly do x>0.5 due to broadCasting
print(x>0.5)
print(x[x>0.5])
#x[x>0.5]=10.0
#print(x)

# we can also use a more complex mask
print((x<0.2) | (x>0.8))



[[0.8808293  0.2354275 ]
 [0.28215077 0.23944031]
 [0.04166704 0.75637203]]
[0.8808293  0.28215077 0.75637203]
[[[0.28215077 0.23944031]
  [0.8808293  0.2354275 ]]

 [[0.28215077 0.23944031]
  [0.8808293  0.2354275 ]]

 [[0.8808293  0.2354275 ]
  [0.28215077 0.23944031]]]
[[ True False]
 [False False]
 [False  True]]
[0.8808293  0.75637203]
[[ True False]
 [False False]
 [ True False]]


## Working with Arrays

<ul>
<li>Arrays concatenation, arrays can be concatenated along axis 0 (as default) and and stacked on top of each other or next to each other, so, <br>h stack to do it horizontally, v stack to do it vertically</li>
<li>arrays split: will split an array into sub arrays, if N == integer, will split the array in N dimensional array (if not multiple error), if N is a 1d array, it specifies which items to split, axis can be specified</li>
<li>I can also reshape an array to change it's component, but we must reshape according to dimension</li>
</ul>

In [68]:
y = np.random.random((3,1))
x = np.random.random((3,2))

print(x)
print(y)
print(np.concatenate([x,y], axis=1))

v = np.array([[1,2,3,4],[5,6,7,8]])
print(np.split(v, 1, axis=0))
print(np.split(v, [1,2]))

print(x.reshape(6))
#numpy will automatically find the last dimension (-1 is a placeholder)
print(x.reshape(2,-1))

print(chr(sum(range(ord(min(str(not())))))))

[[0.11784977 0.09379633]
 [0.33449928 0.40741109]
 [0.95862843 0.60819318]]
[[0.6124695 ]
 [0.59778022]
 [0.93680053]]
[[0.11784977 0.09379633 0.6124695 ]
 [0.33449928 0.40741109 0.59778022]
 [0.95862843 0.60819318 0.93680053]]
[array([[1, 2, 3, 4],
       [5, 6, 7, 8]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int64)]
[0.11784977 0.09379633 0.33449928 0.40741109 0.95862843 0.60819318]
[[0.11784977 0.09379633 0.33449928]
 [0.40741109 0.95862843 0.60819318]]
ඞ
True
